config/routes.rb
Recipefu::Application.routes.draw do
  resources :amounts

  match "/auth/:provider/callback" => "sessions#create"

  root :to => "static#index"

  match "/login" => "sessions#login", :as => :login

  match "/logout" => "sessions#destroy", :as => :logout

  resources :users, :path => '' do
    resources :recipes
    resources :lists
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  
  attr_accessible :title, :description, :instructions, :amounts_attributes
  
  validates :title, :presence => true

  has_friendly_id :title, :use_slug => true, :scope => :user_id
  
  belongs_to :user
  has_many :amounts
  has_many :ingredients, :through => :amounts
  accepts_nested_attributes_for :amounts, :allow_destroy => true
  accepts_nested_attributes_for :ingredients
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :login_required, :except => [:index, :show]
  
  # GET /recipes
  # GET /recipes.xml
  def index

    @user = User.find(params[:user_id])

    @recipes = Recipe.where(:user_id => @user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new
    
    @recipe.amounts.build
    @recipe.ingredients.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.xml
  def create

    @recipe = current_user.recipes.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(user_recipe_path(current_user.cached_slug, @recipe), :notice => 'Recipe was successfully created.') }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = current_user.recipes.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to(user_recipe_path(current_user.id, @recipe), :notice => 'Recipe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = current_user.recipes.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(user_recipes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= nested_form_for([current_user, @recipe]) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "text_field" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description, :class => "text_field" %>
  </div>
  <div class="field">
    <%= f.label :instructions %>
    <%= f.text_area :instructions, :class => "text_field" %>
  </div>

   <% f.fields_for :amounts do |ff| %>  
     <div class="field form_align">  
       <%= ff.label :quantity, "Quantity" %>
       <%= ff.text_field :quantity, :class => "text_field_small" %>  
     </div>
     <div class="field form_align">  
       <%= ff.label :size, "Size" %>
       <%= ff.text_field :size, :class => "text_field_small" %>   
     </div>
     <div class="field">   
       <%= ff.label :ingredient_name, "Ingredient" %>
       <%= ff.text_field :ingredient_name, :class => "text_field" %>
       <%= ff.link_to_remove "remove" %>
     </div>
   <% end %>

   </br></br>

   <%= f.link_to_add "add ingredient", :amounts %>

   </br>

  <div class="send_form actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div id="page">
			
<div class="top"></div>

  <div class="content">
		
    <div class="header page">
	    <h1>Editing recipe</h1>
      <!-- <ul>
        <li class="active"><a href="html_elements.html">HTML Elements</a></li>
        <li><a href="2_column.html">2 Column</a></li>
      </ul> -->
    </div>

    <div id="" class="padding">
  
      <%= render 'form' %>

      <%= link_to 'Show', user_recipe_path(@user) %> |
      <%= link_to 'Back', user_recipes_path %>

    </div>

    <div class="clear"></div>
  
  </div>
  
  <div class="bottom"></div>

</div>

app/views/recipes/index.html.erb
<div id="page">
			
  <div class="top"></div>

    <div class="content">
		
      <div class="header page">
  	    <h1><%= @user.name.downcase %>'s recipes</h1>
      </div>

      <div id="" class="padding">

        <table>

        <% @recipes.each do |recipe| %>
        <tr>
          <td><h3 class="recipe_list"><%= link_to recipe.title, user_recipe_path(:user_id => @user.cached_slug, :id => recipe.cached_slug) %></td>
          <% if current_user %>
            <td><%= link_to 'Edit', edit_user_recipe_path(:user_id => current_user.cached_slug, :id => recipe.cached_slug) %></td>
            <td><%= link_to 'Destroy', user_recipe_path(:user_id => current_user.cached_slug, :id => recipe.cached_slug), :confirm => 'Are you sure?', :method => :delete %></h3></td>
          <% end %>
        </tr>
        <% end %>

        </table>

        <br />

        <% if current_user %>
          <%= link_to 'New Recipe', new_user_recipe_path(:user_id => current_user.cached_slug) %>
        <% end %>
  
      </div>

      <div class="clear"></div>
  
    </div>
  
    <div class="bottom"></div>

</div>

app/views/recipes/new.html.erb
<div id="page">
			
<div class="top"></div>

  <div class="content">
		
    <div class="header page">
	    <h1>New recipe</h1>
      <!-- <ul>
        <li class="active"><a href="html_elements.html">HTML Elements</a></li>
        <li><a href="2_column.html">2 Column</a></li>
      </ul> -->
    </div>

    <div id="" class="padding">

      <%= render 'form' %>

      <%= link_to 'Back', user_recipes_path %>

    </div>

    <div class="clear"></div>
  
  </div>
  
  <div class="bottom"></div>

</div>

app/views/recipes/show.html.erb
<div id="page">

  <div itemscope itemtype="http://schema.org/Recipe">

    <div class="top"></div>

    <div class="content">

      <div class="header page">
        <span itemprop="name"><h1><%= @recipe.title %></h1></span>
      </div>

      <div id="" class="padding">

        <div class="left">

          <% if notice %>
            <p id="notice"><%= notice %></p>
          <% end %>

          <p>
          <span itemprop="recipeInstructions"><%= @recipe.instructions %></span>
          </p>

          <p>
          <b>Ingredients</b>
          </br>
          <% @recipe.amounts.each do |amount| %>
            <span itemprop="ingredients">
              <%= number_with_precision(amount.quantity, :precision => 1, :strip_insignificant_zeros => true) %> <%= amount.size %><% if amount.ingredient %><%= amount.ingredient.name %><% end %></br>
            </span>
          <% end %>
          </p>

          <% if current_user %>
            <%= link_to 'Edit', edit_user_recipe_path(@user) %> |
          <% end %>

          <%= link_to 'Back', user_recipes_path %>

        </div>

        <!-- Start Sidebar -->

        <div class="right">

          <div class="sidebar_box">
            <p>
            <span itemprop="description"><%= @recipe.description %></span>
            </p>
          </div>

        </div>

        <div class="clear"></div>

      </div>

      <!-- End Sidebar -->

    </div>

    <div class="bottom"></div>

  </div>

</div>