config/routes.rb
Recipefu::Application.routes.draw do
  resources :amounts

  match "/auth/:provider/callback" => "sessions#create"

  root :to => "static#index"

  match "/login" => "sessions#login", :as => :login

  match "/logout" => "sessions#destroy", :as => :logout

  resources :users, :path => '' do
    resources :recipes
    resources :lists
  end

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  
  # Need these methods to prevent saving duplicate amounts records
  # http://stackoverflow.com/questions/3579924/accepts-nested-attributes-for-with-find-or-create
  
  def ingredient_name
    ingredient && ingredient.name
  end

  def ingredient_name=(name)
    self.ingredient = Ingredient.find_or_create_by_name(name) unless name.blank?
  end
  
end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController
  # GET /amounts
  # GET /amounts.xml
  def index
    @amounts = Amount.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @amounts }
    end
  end

  # GET /amounts/1
  # GET /amounts/1.xml
  def show
    @amount = Amount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @amount }
    end
  end

  # GET /amounts/new
  # GET /amounts/new.xml
  def new
    @amount = Amount.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @amount }
    end
  end

  # GET /amounts/1/edit
  def edit
    @amount = Amount.find(params[:id])
  end

  # POST /amounts
  # POST /amounts.xml
  def create
    @amount = Amount.new(params[:amount])

    respond_to do |format|
      if @amount.save
        format.html { redirect_to(@amount, :notice => 'Amount was successfully created.') }
        format.xml  { render :xml => @amount, :status => :created, :location => @amount }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @amount.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /amounts/1
  # PUT /amounts/1.xml
  def update
    @amount = Amount.find(params[:id])

    respond_to do |format|
      if @amount.update_attributes(params[:amount])
        format.html { redirect_to(@amount, :notice => 'Amount was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @amount.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /amounts/1
  # DELETE /amounts/1.xml
  def destroy
    @amount = Amount.find(params[:id])
    @amount.destroy

    respond_to do |format|
      format.html { redirect_to(amounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/amounts_helper.rb
module AmountsHelper
end

app/views/amounts/_form.html.erb
<%= form_for(@amount) do |f| %>
  <% if @amount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amount.errors.count, "error") %> prohibited this amount from being saved:</h2>

      <ul>
      <% @amount.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br />
    <%= f.text_field :recipe_id %>
  </div>
  <div class="field">
    <%= f.label :ingredients_id %><br />
    <%= f.text_field :ingredients_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amounts/edit.html.erb
<h1>Editing amount</h1>

<%= render 'form' %>

<%= link_to 'Show', @amount %> |
<%= link_to 'Back', amounts_path %>

app/views/amounts/index.html.erb
<h1>Listing amounts</h1>

<table>
  <tr>
    <th>Quantity</th>
    <th>Size</th>
    <th>Recipe</th>
    <th>Ingredients</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @amounts.each do |amount| %>
  <tr>
    <td><%= amount.quantity %></td>
    <td><%= amount.size %></td>
    <td><%= amount.recipe_id %></td>
    <td><%= amount.ingredients_id %></td>
    <td><%= link_to 'Show', amount %></td>
    <td><%= link_to 'Edit', edit_amount_path(amount) %></td>
    <td><%= link_to 'Destroy', amount, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Amount', new_amount_path %>

app/views/amounts/new.html.erb
<h1>New amount</h1>

<%= render 'form' %>

<%= link_to 'Back', amounts_path %>

app/views/amounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quantity:</b>
  <%= @amount.quantity %>
</p>

<p>
  <b>Size:</b>
  <%= @amount.size %>
</p>

<p>
  <b>Recipe:</b>
  <%= @amount.recipe_id %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @amount.ingredients_id %>
</p>


<%= link_to 'Edit', edit_amount_path(@amount) %> |
<%= link_to 'Back', amounts_path %>