config/routes.rb
Recipefu::Application.routes.draw do
  resources :amounts

  match "/auth/:provider/callback" => "sessions#create"

  root :to => "static#index"

  match "/login" => "sessions#login", :as => :login

  match "/logout" => "sessions#destroy", :as => :logout

  resources :users, :path => '' do
    resources :recipes
    resources :lists
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Fu</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, "nested_form", "site" %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="header">
  <div class="page">
		
    <%= link_to "Home", root_path, :class => "logo" %>

    <div id="user_nav" style="float:right">  
    
    <% if current_user %>  
      Welcome, <%= current_user.name %>!  
      <%= link_to "Log Out", logout_path %>  
    <% else %>  
      <%= link_to "Log In", login_path %>  
    <% end %>  
    
    </div>
		
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if current_user %>
        <li><%= link_to "Recipes", user_recipes_path(:user_id => current_user.cached_slug) %></li>
      <% end %>
      <!-- li class="active"><a href="about.html">About</a></li -->
    </ul> 
   
    <div class="clear"></div>
  </div>
</div>

<%= yield %>

<div id="footer" class="page">
	<p>&copy; 2011 - <%= Time.now.year %> raygun consulting inc.</p>
  <!-- <ul>
    <li><a href="index.html">Home</a></li>
    <li><a href="about.html">About</a></li>
    <li><a href="tour.html">Tour</a></li>
    <li><a href="pricing.html">Pricing</a></li>
    <li><a href="blog.html">Blog</a></li>
    <li><a href="contact.html">Contact</a></li>
  </ul> -->
	<div class="clear"></div>
</div>
	
</body>
</html>